# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kaiwu_msg

class ReqMsg(object):
    NONE = 0
    init_req = 1
    ep_start_req = 2
    agent_start_req = 3
    update_req = 4
    agent_end_req = 5
    ep_end_req = 6
    event_req = 7
    quit = 8
    heartbeat = 9
