# automatically generated by the FlatBuffers compiler, do not modify

# namespace: kaiwu_msg

class RspMsg(object):
    NONE = 0
    init_rsp = 1
    ep_start_rsp = 2
    agent_start_rsp = 3
    update_rsp = 4
    agent_end_rsp = 5
    ep_end_rsp = 6
    event_rsp = 7
    restart = 8
    reject = 9
