# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aisrv_actor_req_resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aisrv_actor_req_resp.proto',
  package='kaiwu_aisvr',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x1a\x61isrv_actor_req_resp.proto\x12\x0bkaiwu_aisvr\x1a google/protobuf/descriptor.proto\"`\n\x11\x41isrvActorRequest\x12\x11\n\tclient_id\x18\x01 \x02(\x05\x12\x12\n\ncompose_id\x18\x02 \x03(\x05\x12\x0f\n\x07\x66\x65\x61ture\x18\x03 \x03(\x02\x12\x13\n\x0bsample_size\x18\x04 \x02(\x05\"8\n\x12\x41isrvActorResponse\x12\x12\n\ncompose_id\x18\x01 \x03(\x05\x12\x0e\n\x06output\x18\x02 \x03(\x02\x42\x02H\x03')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])




_AISRVACTORREQUEST = _descriptor.Descriptor(
  name='AisrvActorRequest',
  full_name='kaiwu_aisvr.AisrvActorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_id', full_name='kaiwu_aisvr.AisrvActorRequest.client_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compose_id', full_name='kaiwu_aisvr.AisrvActorRequest.compose_id', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature', full_name='kaiwu_aisvr.AisrvActorRequest.feature', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sample_size', full_name='kaiwu_aisvr.AisrvActorRequest.sample_size', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=173,
)


_AISRVACTORRESPONSE = _descriptor.Descriptor(
  name='AisrvActorResponse',
  full_name='kaiwu_aisvr.AisrvActorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='compose_id', full_name='kaiwu_aisvr.AisrvActorResponse.compose_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output', full_name='kaiwu_aisvr.AisrvActorResponse.output', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=231,
)

DESCRIPTOR.message_types_by_name['AisrvActorRequest'] = _AISRVACTORREQUEST
DESCRIPTOR.message_types_by_name['AisrvActorResponse'] = _AISRVACTORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AisrvActorRequest = _reflection.GeneratedProtocolMessageType('AisrvActorRequest', (_message.Message,), {
  'DESCRIPTOR' : _AISRVACTORREQUEST,
  '__module__' : 'aisrv_actor_req_resp_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AisrvActorRequest)
  })
_sym_db.RegisterMessage(AisrvActorRequest)

AisrvActorResponse = _reflection.GeneratedProtocolMessageType('AisrvActorResponse', (_message.Message,), {
  'DESCRIPTOR' : _AISRVACTORRESPONSE,
  '__module__' : 'aisrv_actor_req_resp_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AisrvActorResponse)
  })
_sym_db.RegisterMessage(AisrvActorResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
