# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aisrv_learner_req_resp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='aisrv_learner_req_resp.proto',
  package='kaiwu_aisvr',
  syntax='proto2',
  serialized_options=_b('H\003'),
  serialized_pb=_b('\n\x1c\x61isrv_learner_req_resp.proto\x12\x0bkaiwu_aisvr\x1a google/protobuf/descriptor.proto\"7\n\x13\x41isrvLearnerRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x02\x12\x12\n\nbatch_size\x18\x02 \x02(\x05\x42\x02H\x03')
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])




_AISRVLEARNERREQUEST = _descriptor.Descriptor(
  name='AisrvLearnerRequest',
  full_name='kaiwu_aisvr.AisrvLearnerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='kaiwu_aisvr.AisrvLearnerRequest.data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='kaiwu_aisvr.AisrvLearnerRequest.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['AisrvLearnerRequest'] = _AISRVLEARNERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AisrvLearnerRequest = _reflection.GeneratedProtocolMessageType('AisrvLearnerRequest', (_message.Message,), {
  'DESCRIPTOR' : _AISRVLEARNERREQUEST,
  '__module__' : 'aisrv_learner_req_resp_pb2'
  # @@protoc_insertion_point(class_scope:kaiwu_aisvr.AisrvLearnerRequest)
  })
_sym_db.RegisterMessage(AisrvLearnerRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
